### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Walter-pixel** [xjtushujun/Meta-weight-net_class-imbalance#1]
Hi, I tried to run the code but it keeps throwing out "AttributeError: Can't pickle local object 'build_dataset.<locals>.<lambda>'
". I used the exact same configuration: Python 3+/PyTorch 0.4.0/Torchvision 0.2.0. Could you please provide me some hints to resolve this problem? Thanks

**Comment by xjtushujun** [comment]
Are you using Windows operating system？
